# Generated by Django 4.0.4 on 2022-04-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('date_incorporation', models.DateField()),
                ('company_address_1', models.CharField(max_length=200)),
                ('company_address_2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=100)),
                ('dob', models.DateField(auto_now_add=True, verbose_name='Date of Birth')),
                ('nationality', models.CharField(max_length=50)),
                ('citizenship', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=200)),
                ('identity_type', models.CharField(max_length=200)),
                ('nric_no', models.CharField(max_length=200)),
                ('passport_no', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_test.account')),
            ],
        ),
    ]
