# Generated by Django 4.0.4 on 2022-04-20 06:24

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('react_test', '0001_initial'),
    ]

    operations = [
    ]
