# Generated by Django 4.0.4 on 2022-04-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_test', '0002_react_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_incorporation',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Incorporation'),
        ),
    ]
