# Generated by Django 4.0.4 on 2022-04-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('react_test', '0003_alter_account_date_incorporation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='company_address_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='company_address_2',
            new_name='address_2',
        ),
    ]
