# Generated by Django 4.0.4 on 2022-04-20 06:34

from django.db import migrations

def create_data(apps, schema_editor):
    Account = apps.get_model('react_test', 'Account')
    Account(company_name='aptvise', date_incorporation='2022 4 20', address_1='sg', address_2='my').save()

class Migration(migrations.Migration):

    dependencies = [
        ('react_test', '0004_rename_company_address_1_account_address_1_and_more'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
