# Generated by Django 4.0.4 on 2022-04-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_test', '0005_react_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_id',
            field=models.CharField(default='Your company id', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='address_1',
            field=models.CharField(default='company address 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='address_2',
            field=models.CharField(default='company address 2', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.CharField(default='Your company name', max_length=100),
        ),
    ]
